version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Running tests (if any)..."
      - npm test || echo "No tests found"
      - echo "Build step (if any)..."
      - npm run build || echo "No build step"
artifacts:
  files:
    - '**/*'
